
kind: pipeline
name: default

clone:
  disable: true

workspace:
  path: /app/src

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/StarGate01/flexsecure-applets .
  - git -c submodule."smartcard-ci".update=none submodule update --init --recursive
- name: build  
  image: stargate01/smartcard-ci
  commands:
  - /app/src/scripts/compile.sh



    