
kind: pipeline
name: default

clone:
  disable: true

workspace:
  path: /app/src

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/StarGate01/flexsecure-applets .
  - git -c submodule."smartcard-ci".update=none submodule update --init --recursive
- name: build  
  image: stargate01/smartcard-ci
  commands:
  - /app/src/scripts/compile-all.sh
- name: test  
  image: stargate01/smartcard-ci
  commands:
  - /app/src/scripts/test-all.sh
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    files: /app/src/bin/*
  when:
    branch:
    - master
    event:
    - tag
